kubernetes apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      namespace: backend-k8s
  template:
    metadata:
      labels:
        app: backend
        namespace: backend-k8s
    spec:
      containers:
      - name: backend-deployment
        image: 288096932508.dkr.ecr.ap-south-1.amazonaws.com/backend:5
        ports:
        - containerPort: 8000
